pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker') {
            steps {
                sh 'docker build -t mysite -f docker/Dockerfile .'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker stop mysite || true
                docker rm mysite || true
                docker run -d -p 80:80 --name mysite mysite
                '''
            }
        }
    }
}
